# ECON 523:  PROGRAM EVALUATION FOR INTERNATIONAL DEVELOPMENT
# PROFESSOR PAMELA JAKIELA
# EMPIRICAL EXERCISE 2, PART 2:  SELECTION BIAS AND THE EXPERIMENTAL IDEAL
# 
# 
# ***************************************************************************
#   In this exercise, we'll use R's rnorm() command to generate draws from 
# a normally-distributed random variable.  This approach - simulating data 
# according to a known data-generating process - is an incredibly useful tool 
# in empirical microeconomics (both for checking your econometric intuitions and 
#                              your anlayis code).  
# 
# We'll use variables to easily change the number of 
# observations and other parameters of our data set.  This will allow us to 
# explore the way the properties of randomly-assigned treatment groups in 
# larger and smaller samples.
# 
# ******************************************************************************


# PRELIMINARIES
# 
# Before anything else, run this line:

set.seed(523)

# This will ensure that the `rnorm()` function (which, as mentioned, 
# randomly samples from a normal distribution) will generate the same
# numbers every time you run your code. If you don't do this, all of your
# answers will be wrong!  


# GENERATE A DATA SET
# 
# Define a variable that we'll use to indicate the number of observations:
myobs <- 500

# Creating some variables
y <- rnorm(myObs)
z <- 5 * rnorm(500) + 10




# EMPIRICAL EXERCISE
# 
# Question 1 
# 
# What is the mean of `z`?  



# Question 2 
# 
# Use the command `mean_z <- mean(z)` to generate a new variable equal to the
# mean of `z`.  What is the standard deviation of your new variable, `mean_z`?



# Question 3
# 
# Generate another variable, `diff_z`, equal to the difference between `z`
# and `mean_z`.  What is the mean of this variable?



# Question 4 
# 
# yet another new variable, this one equal to `diff_z` squared.  Call this
# variable `diff2_z`.  Now use the code below to calculate the sum of
# diff2_z` across all observations, and to transform that sum into the
# standard deviation of `z` by dividing by the number of observations and
# then taking the square root.  

sd_z <- sum(diff2_z)
sd_z <- sd_z / (myobs - 1)
sd_z <- sqrt(sd_z)

# What is the value of `sd_z`?
  
  
  
  
# Question 5 
# 
# Our estimator of the **population** mean of `z` is the sample mean of `z`,
# and the standard error of that estimator is the sample standard deviation
# (that you calculated above) divided by the square root of the number of
# observations in your sample.  Write a line of code to generate a new
# variable, `se_mean_z`, equal to the standard error of the mean of `z`.


# Question 6 
# 
# What is the standard error of the mean of `z`?  Confirm that the answer
# generated by the code you wrote for Question 5 is the same as the answer
# you'd get from the`t.test(z)$stderr` command.



# Question 7 
# 
# What happens when we randomly assign treatment?  Random assignment should
# generate two groups (a treatment group and a control group) that look
# similar in terms of their observable characteristics.  We can use the code
# below to assign half the observations in our sample to a treatment group.


# Assign half the sample (observations 1 to myObs / 2) to treatment:
treatment <- c(rep(1, floor(myObs / 2)), rep(0, ceiling(myObs / 2)))


# If we were randomly assigning treatment in a data set that we had not just
# generated, we would first want to sort our data into a random
# order - but here, that is not necessary since `y` and `z` are
# randomly-generated to begin with.  

# Now that you have generated a treatment dummy variable, test the
# hypothesis that the mean of `z` is the same in the treatment group and the
# comparison group.  What is the p-value associated with this hypothesis
# test?  